const express = require('express');
const app = express();
const cors = require('cors');
app.use(cors());
const Signup = require("./routes/Signup");
const Signin =  require("./routes/Signin");
const JobRegister = require("./routes/JobRegister");
const CompanyRegister = require ("./routes/companyRegister");
const Stats =  require ("./routes/Stats");
const SeachJobs = require("./routes/searchJobs");
const applyJobs = require("./routes/applyJobs");
app.use('/Signup', Signup);
app.use("/Signin", Signin);
app.use("/register-job", JobRegister);
app.use("/register-company", CompanyRegister);
app.use("/stats", Stats);
app.use("/search",SeachJobs);
app.use("/apply",applyJobs);
module.exports = app;
